### ISSUE TITLE
Add 'earliest stable block for a given version' to contract reference page

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport-docs#102]
If you don't use a recent OP block, you will get the error, `GitcoinResolver.NotAllowListed()`

Developers will want to fork after this block: 115525426

I'm honestly not too sure how or where to include this, so when you get to this ticket, please DM me so we can discuss.

**Comment by jmcook1186** [comment]
added info to test mode page (i think this is a very niche requirement - most people will not use very old blocks to create forked testnets)
