### ISSUE TITLE
Update list of decoder onchain networks

### ISSUE THREAD

**Issue by lebraat** [gitcoinco/passport-docs#89]
Remove OP Goerli and Base Goerli

Add Linea mainnet

**Comment by Onoscity** [comment]
Link not available?

**Comment by lebraat** [comment]
We're waiting for our tech lead to get back to verify a few things before we add, but it's coming soon!

**Comment by lebraat** [comment]
@nutrina -- Do we have plans to deploy the decoder to a Linea testnet as well?

**Comment by lebraat** [comment]
[Onchain Passport] Deploy onchain Passport to Linea Testnet #2268
