### ISSUE TITLE
No test endpoint at https://api.scorer.gitcoin.co/endpoint

### ISSUE THREAD

**Issue by minhoryang** [gitcoinco/passport-docs#9]
https://docs.passport.gitcoin.co/building-with-passport/scorer-api/api-access#using-your-x-api-key

said `curl -H "X-API-KEY: {API_KEY}" https://api.scorer.gitcoin.co/endpoint`, but I got

```html
<!doctype html>
<html lang="en">
<head>
  <title>Not Found</title>
</head>
<body>
  <h1>Not Found</h1><p>The requested resource was not found on this server.</p>
</body>
</html>
```

**Comment by jmcook1186** [comment]
You need to replace the word "endpoint" in the request with the actual endpoint you want to use,
e.g.  `https://api.scorer.gitcoin.co/registry/score/{args}`
see here for the endpoint definitions and examples
https://docs.passport.gitcoin.co/building-with-passport/scorer-api/endpoint-definition
